import { type FormEvent, useState } from 'react';
import type { EntityInput } from '../../db/repositories';
import type { LearningMethod } from '../../domain/entities';
import { Button } from '../../shared/ui/Button';
import { ConfirmDialog } from '../../shared/ui/ConfirmDialog';
import { Dialog } from '../../shared/ui/Dialog';
import { EmptyState } from '../../shared/ui/EmptyState';
import { Field } from '../../shared/ui/Field';
import { useCreateLearningMethod, useDeleteLearningMethod, useLearningMethods, useUpdateLearningMethod } from './researchQueries';

const tags = (value: string) => [...new Set(value.split(/[,，\s]+/).map((tag) => tag.trim()).filter(Boolean))];
function MethodForm({ initial, onSaved }: { initial?: LearningMethod; onSaved: () => void }) {
  const [values, setValues] = useState({ name: initial?.name ?? '', scenario: initial?.scenario ?? '', steps: initial?.steps ?? '', evaluation: initial?.evaluation ?? '', tags: initial?.tags.join(', ') ?? '' }); const [error, setError] = useState(''); const create = useCreateLearningMethod(); const update = useUpdateLearningMethod();
  const submit = async (e: FormEvent) => { e.preventDefault(); if (!values.name.trim()) { setError('请填写名称'); return; } const input: EntityInput<LearningMethod> = { name: values.name.trim(), scenario: values.scenario.trim(), steps: values.steps.trim(), evaluation: values.evaluation.trim(), tags: tags(values.tags) }; try { if (initial) await update.mutateAsync({ id: initial.id, patch: input }); else await create.mutateAsync(input); onSaved(); } catch { setError('保存失败，请重试'); } };
  return <form className="research-form" onSubmit={submit}><Field label="名称" required value={values.name} onChange={(e) => setValues({ ...values, name: e.target.value })} /><label className="field"><span className="field-label">适用场景</span><textarea value={values.scenario} onChange={(e) => setValues({ ...values, scenario: e.target.value })} /></label><label className="field"><span className="field-label">步骤</span><textarea value={values.steps} onChange={(e) => setValues({ ...values, steps: e.target.value })} /></label><label className="field"><span className="field-label">效果评价</span><textarea value={values.evaluation} onChange={(e) => setValues({ ...values, evaluation: e.target.value })} /></label><Field label="标签" value={values.tags} onChange={(e) => setValues({ ...values, tags: e.target.value })} />{error && <p className="form-errors" role="alert">{error}</p>}<div className="dialog-actions"><Button type="submit">保存</Button></div></form>;
}
export function LearningMethodPanel() {
  const query = useLearningMethods(); const remove = useDeleteLearningMethod(); const [editing, setEditing] = useState<LearningMethod | null>(null); const [open, setOpen] = useState(false); const [deleting, setDeleting] = useState<LearningMethod | null>(null); const close = () => { setOpen(false); setEditing(null); };
  return <section className="learning-method-panel" aria-labelledby="learning-methods-title"><header className="section-header"><div><h3 id="learning-methods-title">学习方法</h3><p>独立保存可复用的学习方法。</p></div><Button onClick={() => { setEditing(null); setOpen(true); }}>新建学习方法</Button></header>{query.isPending && <p role="status">正在加载学习方法……</p>}{query.isError && <p role="alert">学习方法加载失败，请重试。</p>}{!query.isPending && !query.isError && query.data?.length === 0 && <EmptyState title="暂无学习方法" description="记录适用场景、步骤和评价。" />}{query.data && query.data.length > 0 && <ul className="content-cards">{query.data.map((method) => <li key={method.id}><div><h4>{method.name}</h4><p><strong>适用场景：</strong>{method.scenario || '未填写'}</p><p><strong>步骤：</strong>{method.steps || '未填写'}</p><p>{method.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</p></div><div className="card-actions"><Button aria-label={`编辑${method.name}`} variant="ghost" onClick={() => { setEditing(method); setOpen(true); }}>编辑</Button><Button aria-label={`删除${method.name}`} variant="ghost" onClick={() => setDeleting(method)}>删除</Button></div></li>)}</ul>}<Dialog open={open} onClose={close} title={editing ? '编辑学习方法' : '新建学习方法'}><MethodForm initial={editing ?? undefined} onSaved={close} /></Dialog><ConfirmDialog confirmLabel="删除" onClose={() => setDeleting(null)} onConfirm={() => deleting && remove.mutate(deleting.id, { onSuccess: () => setDeleting(null) })} open={!!deleting} title="删除学习方法"><p>删除“{deleting?.name}”不会删除已引用它的业务记录。</p></ConfirmDialog></section>;
}
