import { useMemo, useState } from 'react';
import type { ResearchItem } from '../../domain/entities';
import { Button } from '../../shared/ui/Button';
import { ConfirmDialog } from '../../shared/ui/ConfirmDialog';
import { Dialog } from '../../shared/ui/Dialog';
import { EmptyState } from '../../shared/ui/EmptyState';
import { LearningMethodPanel } from './LearningMethodPanel';
import { ResearchForm } from './ResearchForm';
import { useDeleteResearch, useResearchItems } from './researchQueries';

const statusName = { unread: '待读', reading: '阅读中', read: '已读' };
export function ResearchPage() {
  const query = useResearchItems(); const remove = useDeleteResearch(); const [filters, setFilters] = useState({ search: '', status: 'all', year: 'all', tag: 'all' }); const [editing, setEditing] = useState<ResearchItem | null>(null); const [open, setOpen] = useState(false); const [deleting, setDeleting] = useState<ResearchItem | null>(null);
  const years = useMemo(() => [...new Set((query.data ?? []).map((item) => item.year).filter((year): year is number => year !== null))].sort((a, b) => b - a), [query.data]); const tags = useMemo(() => [...new Set((query.data ?? []).flatMap((item) => item.tags))].sort(), [query.data]); const items = useMemo(() => { const search = filters.search.trim().toLocaleLowerCase(); return (query.data ?? []).filter((item) => (!search || `${item.title} ${item.authors} ${item.source} ${item.abstract} ${item.notes} ${item.tags.join(' ')}`.toLocaleLowerCase().includes(search)) && (filters.status === 'all' || item.status === filters.status) && (filters.year === 'all' || item.year === Number(filters.year)) && (filters.tag === 'all' || item.tags.includes(filters.tag))).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }, [filters, query.data]);
  const close = () => { setOpen(false); setEditing(null); };
  return <section className="research-page" aria-labelledby="research-page-title"><header className="page-header"><div><h2 id="research-page-title">个人科研</h2><p>沉淀文献与可复用的学习方法。</p></div><Button onClick={() => { setEditing(null); setOpen(true); }}>新建文献</Button></header><div className="research-filters"><label className="field"><span className="field-label">搜索文献</span><input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /></label><label className="field"><span className="field-label">阅读状态</span><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="all">全部状态</option><option value="unread">待读</option><option value="reading">阅读中</option><option value="read">已读</option></select></label><label className="field"><span className="field-label">年份</span><select value={filters.year} onChange={(e) => setFilters({ ...filters, year: e.target.value })}><option value="all">全部年份</option>{years.map((year) => <option key={year} value={year}>{year}</option>)}</select></label><label className="field"><span className="field-label">标签</span><select value={filters.tag} onChange={(e) => setFilters({ ...filters, tag: e.target.value })}><option value="all">全部标签</option>{tags.map((tag) => <option key={tag} value={tag}>{tag}</option>)}</select></label></div>{query.isPending && <p role="status">正在加载文献……</p>}{query.isError && <p role="alert">文献加载失败，请刷新后重试。</p>}{!query.isPending && !query.isError && items.length === 0 && <EmptyState title={query.data?.length ? '没有匹配文献' : '暂无文献'} description={query.data?.length ? '请调整筛选条件。' : '添加一条文献记录开始积累。'} />}{items.length > 0 && <ul className="content-cards">{items.map((item) => <li key={item.id}><div><h3>{item.title}</h3><p>{item.authors}{item.year ? ` · ${item.year}` : ''}{item.source ? ` · ${item.source}` : ''}</p><p><span className="status-badge">{statusName[item.status]}</span>{item.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</p>{item.notes && <p>{item.notes}</p>}</div><div className="card-actions"><Button aria-label={`编辑${item.title}`} variant="ghost" onClick={() => { setEditing(item); setOpen(true); }}>编辑</Button><Button aria-label={`删除${item.title}`} variant="ghost" onClick={() => setDeleting(item)}>删除</Button></div></li>)}</ul>}<LearningMethodPanel /><Dialog open={open} onClose={close} title={editing ? '编辑文献' : '新建文献'}><ResearchForm initial={editing ?? undefined} onSaved={close} /></Dialog><ConfirmDialog confirmLabel="删除" onClose={() => setDeleting(null)} onConfirm={() => deleting && remove.mutate(deleting.id, { onSuccess: () => setDeleting(null) })} open={!!deleting} title="删除文献"><p>确定删除“{deleting?.title}”吗？</p></ConfirmDialog></section>;
}
