import { type FormEvent, useState } from 'react';
import { useDirtyForm } from '../../app/usePwaUpdate';
import type { LessonPlanInput } from '../../db/repositories';
import type { Course, LessonPlan } from '../../domain/entities';
import { Button } from '../../shared/ui/Button';
import { Field } from '../../shared/ui/Field';
import { useCreateLessonPlan, useUpdateLessonPlan } from './lessonQueries';

export function LessonForm({ courses, initial, onSaved }: { courses: Course[]; initial?: LessonPlan; onSaved: (plan: LessonPlan) => void }) {
  const [values, setValues] = useState({ courseId: initial?.courseId ?? '', chapter: initial?.chapter ?? '', objectives: initial?.objectives ?? '', outline: initial?.outline ?? '', resources: initial?.resources ?? '', activities: initial?.activities ?? '', plannedDate: initial?.plannedDate ?? '', status: initial?.status ?? 'notStarted' as LessonPlan['status'] }); const [error, setError] = useState(''); const create = useCreateLessonPlan(); const update = useUpdateLessonPlan();
  useDirtyForm(JSON.stringify(values) !== JSON.stringify({ courseId: initial?.courseId ?? '', chapter: initial?.chapter ?? '', objectives: initial?.objectives ?? '', outline: initial?.outline ?? '', resources: initial?.resources ?? '', activities: initial?.activities ?? '', plannedDate: initial?.plannedDate ?? '', status: initial?.status ?? 'notStarted' }));
  const submit = async (e: FormEvent) => { e.preventDefault(); if (!values.chapter.trim() && !values.outline.trim()) { setError('请至少填写章节或内容提纲'); return; } const input: LessonPlanInput = { courseId: values.courseId || null, chapter: values.chapter.trim(), objectives: values.objectives.trim(), outline: values.outline.trim(), resources: values.resources.trim(), activities: values.activities.trim(), plannedDate: values.plannedDate || null, status: values.status, sourceType: initial?.sourceType ?? null, sourceId: initial?.sourceId ?? null }; try { onSaved(initial ? await update.mutateAsync({ id: initial.id, patch: input }) : await create.mutateAsync(input)); } catch { setError('保存失败，请重试'); } };
  return <form className="lesson-form" onSubmit={submit}><label className="field"><span className="field-label">课程</span><select value={values.courseId} onChange={(e) => setValues({ ...values, courseId: e.target.value })}><option value="">未关联课程</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label><Field label="章节" value={values.chapter} onChange={(e) => setValues({ ...values, chapter: e.target.value })} /><label className="field"><span className="field-label">教学目标</span><textarea value={values.objectives} onChange={(e) => setValues({ ...values, objectives: e.target.value })} /></label><label className="field"><span className="field-label">内容提纲</span><textarea value={values.outline} onChange={(e) => setValues({ ...values, outline: e.target.value })} /></label><label className="field"><span className="field-label">教学资源</span><textarea value={values.resources} onChange={(e) => setValues({ ...values, resources: e.target.value })} /></label><label className="field"><span className="field-label">课堂活动</span><textarea value={values.activities} onChange={(e) => setValues({ ...values, activities: e.target.value })} /></label><div className="lesson-form-grid"><Field label="计划日期" type="date" value={values.plannedDate} onChange={(e) => setValues({ ...values, plannedDate: e.target.value })} /><label className="field"><span className="field-label">进度</span><select value={values.status} onChange={(e) => setValues({ ...values, status: e.target.value as LessonPlan['status'] })}><option value="notStarted">未开始</option><option value="inProgress">进行中</option><option value="done">已完成</option></select></label></div>{error && <p className="form-errors" role="alert">{error}</p>}<div className="dialog-actions"><Button type="submit">保存</Button></div></form>;
}
