import { type FormEvent, useState } from 'react';
import { useDirtyForm } from '../../app/usePwaUpdate';
import type { EntityInput } from '../../db/repositories';
import type { StudentRecord } from '../../domain/entities';
import { Button } from '../../shared/ui/Button';
import { Field } from '../../shared/ui/Field';
import { useCreateStudentRecord } from './studentQueries';

export function StudentRecordForm({ studentId, onSaved }: { studentId: string; onSaved: () => void }) {
  const create = useCreateStudentRecord(); const [values, setValues] = useState({ date: new Date().toISOString().slice(0, 10), category: 'task' as StudentRecord['category'], rating: 'positive' as StudentRecord['rating'], content: '', followUp: '', tags: '' });
  useDirtyForm(Boolean(values.content || values.followUp || values.tags));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!values.content.trim()) return; await create.mutateAsync({ studentId, date: values.date, category: values.category, rating: values.rating, content: values.content.trim(), followUp: values.followUp.trim(), tags: values.tags.split(/[,，]/).map((tag) => tag.trim()).filter(Boolean) } satisfies EntityInput<StudentRecord>); onSaved(); };
  return <form className="course-form" onSubmit={submit}><Field label="日期" required type="date" value={values.date} onChange={(event) => setValues({ ...values, date: event.target.value })} /><label className="field"><span className="field-label">类别</span><select aria-label="类别" value={values.category} onChange={(event) => setValues({ ...values, category: event.target.value as StudentRecord['category'] })}><option value="task">任务推进</option><option value="attendance">出勤表现</option><option value="research">科研学习</option><option value="service">班级服务</option><option value="other">其他</option></select></label><label className="field"><span className="field-label">等级</span><select aria-label="等级" value={values.rating} onChange={(event) => setValues({ ...values, rating: event.target.value as StudentRecord['rating'] })}><option value="positive">积极</option><option value="normal">一般</option><option value="attention">需关注</option></select></label><label className="field"><span className="field-label">内容</span><textarea aria-label="内容" required value={values.content} onChange={(event) => setValues({ ...values, content: event.target.value })} /></label><label className="field"><span className="field-label">后续跟进</span><textarea aria-label="后续跟进" value={values.followUp} onChange={(event) => setValues({ ...values, followUp: event.target.value })} /></label><Field aria-label="标签" label="标签" value={values.tags} onChange={(event) => setValues({ ...values, tags: event.target.value })} hint="以逗号分隔" />{create.isError && <p role="alert">保存失败，请重试。</p>}<div className="dialog-actions"><Button disabled={create.isPending} type="submit">保存</Button></div></form>;
}
