import { type FormEvent, useMemo, useRef, useState } from 'react';
import type { Student } from '../../domain/entities';
import { Button } from '../../shared/ui/Button';
import { Dialog } from '../../shared/ui/Dialog';
import { Field } from '../../shared/ui/Field';
import { StudentDetail } from './StudentDetail';
import { StudentList } from './StudentList';
import { StudentSummary } from './StudentSummary';
import { useArchiveStudent, useCreateStudent, useDeleteStudentWithRecords, useStudentRecords, useStudents, useUpdateStudent } from './studentQueries';

function StudentForm({ initial, onSaved }: { initial?: Student; onSaved: () => void }) {
  const create = useCreateStudent(); const update = useUpdateStudent(); const [values, setValues] = useState({ name: initial?.name ?? '', program: initial?.program ?? '', cohort: initial?.cohort ?? '', contact: initial?.contact ?? '', notes: initial?.notes ?? '' });
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!values.name.trim() || !values.program.trim() || !values.cohort.trim()) return; const value = { name: values.name.trim(), program: values.program.trim(), cohort: values.cohort.trim(), contact: values.contact.trim(), notes: values.notes.trim() }; if (initial) await update.mutateAsync({ id: initial.id, patch: value }); else await create.mutateAsync({ ...value, archivedAt: null }); onSaved(); };
  return <form className="course-form" onSubmit={submit}><Field label="学生姓名" required value={values.name} onChange={(event) => setValues({ ...values, name: event.target.value })} /><Field label="培养项目" required value={values.program} onChange={(event) => setValues({ ...values, program: event.target.value })} /><Field label="年级" required value={values.cohort} onChange={(event) => setValues({ ...values, cohort: event.target.value })} /><Field label="联系方式" value={values.contact} onChange={(event) => setValues({ ...values, contact: event.target.value })} /><label className="field"><span className="field-label">备注</span><textarea value={values.notes} onChange={(event) => setValues({ ...values, notes: event.target.value })} /></label>{(create.isError || update.isError) && <p role="alert">保存失败，请重试。</p>}<div className="dialog-actions"><Button disabled={create.isPending || update.isPending} type="submit">保存</Button></div></form>;
}
function StudentRemovalDialog({ recordCount, onArchive, onClose, onDelete, open, student }: { recordCount: number; onArchive: () => void; onClose: () => void; onDelete: () => void; open: boolean; student: Student | null }) { const archiveButton = useRef<HTMLButtonElement>(null); return <Dialog initialFocusRef={archiveButton} open={open} onClose={onClose} title="处理学生记录"><p aria-label={`关联日常记录：${recordCount} 条`}>“{student?.name}”关联日常记录：{recordCount} 条</p><p>归档会保留学生与全部日常记录；删除会永久移除两者。</p><div className="dialog-actions"><Button variant="secondary" onClick={onClose}>取消</Button><Button onClick={onArchive} ref={archiveButton}>归档学生</Button><Button variant="danger" onClick={onDelete}>删除学生及记录</Button></div></Dialog>; }

export function StudentPage() {
  const studentsQuery = useStudents(); const recordsQuery = useStudentRecords(); const archive = useArchiveStudent(); const remove = useDeleteStudentWithRecords(); const [tab, setTab] = useState<'roster' | 'summary'>('roster'); const [editing, setEditing] = useState<Student | null>(null); const [detail, setDetail] = useState<Student | null>(null); const [removing, setRemoving] = useState<Student | null>(null);
  const students = studentsQuery.data ?? []; const records = recordsQuery.data ?? []; const activeStudents = useMemo(() => students.filter((student) => student.archivedAt === null).sort((a, b) => a.name.localeCompare(b.name)), [students]); const recordCount = removing ? records.filter((record) => record.studentId === removing.id).length : 0; const loading = studentsQuery.isPending || recordsQuery.isPending; const closeRemoval = () => setRemoving(null);
  return <section className="student-page" aria-labelledby="student-page-title"><header className="page-header"><div><h2 id="student-page-title">学生管理</h2><p>维护学生名册、个人日常记录与多条件汇总。</p></div><div className="page-actions"><Button onClick={() => setEditing({} as Student)}>新增学生</Button></div></header><div className="view-switch" role="group" aria-label="学生管理标签"><Button aria-pressed={tab === 'roster'} variant={tab === 'roster' ? 'primary' : 'secondary'} onClick={() => setTab('roster')}>学生名册</Button><Button aria-pressed={tab === 'summary'} variant={tab === 'summary' ? 'primary' : 'secondary'} onClick={() => setTab('summary')}>学生记录汇总</Button></div>{loading && <p role="status">正在加载学生数据……</p>}{!loading && tab === 'roster' && <StudentList students={activeStudents} onDelete={setRemoving} onEdit={setEditing} onView={setDetail} />}{!loading && tab === 'summary' && <StudentSummary records={records} students={students} />}<Dialog open={editing !== null} onClose={() => setEditing(null)} title={editing?.id ? '编辑学生' : '新增学生'}><StudentForm initial={editing?.id ? editing : undefined} onSaved={() => setEditing(null)} /></Dialog><Dialog open={detail !== null} onClose={() => setDetail(null)} title={`${detail?.name ?? ''}详情`}>{detail && <StudentDetail records={records} student={detail} />}</Dialog><StudentRemovalDialog open={removing !== null} student={removing} recordCount={recordCount} onClose={closeRemoval} onArchive={() => { if (removing) archive.mutate(removing.id, { onSuccess: closeRemoval }); }} onDelete={() => { if (removing) remove.mutate(removing.id, { onSuccess: closeRemoval }); }} /></section>;
}
