import { useMemo, useState } from 'react';
import type { Student, StudentRecord } from '../../domain/entities';
import { studentRecordCategoryLabels, studentRecordRatingLabels } from '../../domain/studentOperations';
import { Button } from '../../shared/ui/Button';
import { Dialog } from '../../shared/ui/Dialog';
import { ConfirmDialog } from '../../shared/ui/ConfirmDialog';
import { StudentRecordForm } from './StudentRecordForm';
import { useDeleteStudentRecord } from './studentQueries';

export function StudentDetail({ student, records }: { student: Student; records: StudentRecord[] }) {
  const [recordFormOpen, setRecordFormOpen] = useState(false); const [editing, setEditing] = useState<StudentRecord | null>(null); const [deleting, setDeleting] = useState<StudentRecord | null>(null); const remove = useDeleteStudentRecord(); const studentRecords = useMemo(() => records.filter((record) => record.studentId === student.id).sort((a, b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt)), [records, student.id]);
  return <section><dl className="course-detail"><div><dt>培养项目</dt><dd>{student.program}</dd></div><div><dt>年级</dt><dd>{student.cohort}</dd></div><div><dt>联系方式</dt><dd>{student.contact}</dd></div><div><dt>备注</dt><dd>{student.notes || '—'}</dd></div></dl><div className="page-actions"><Button onClick={() => setRecordFormOpen(true)}>添加日常记录</Button></div>{studentRecords.length ? <ul className="student-record-list">{studentRecords.map((record) => <li key={record.id}><strong>{record.content}</strong><span>{record.date} · {studentRecordCategoryLabels[record.category]} · {studentRecordRatingLabels[record.rating]}</span>{record.followUp && <p>跟进：{record.followUp}</p>}{record.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}<div className="card-actions"><Button aria-label={`编辑${record.content}`} variant="ghost" onClick={() => setEditing(record)}>编辑</Button><Button aria-label={`删除${record.content}`} variant="ghost" onClick={() => setDeleting(record)}>删除</Button></div></li>)}</ul> : <p>暂无日常记录。</p>}<Dialog open={recordFormOpen} onClose={() => setRecordFormOpen(false)} title="添加日常记录"><StudentRecordForm studentId={student.id} onSaved={() => setRecordFormOpen(false)} /></Dialog><Dialog open={editing !== null} onClose={() => setEditing(null)} title="编辑日常记录">{editing && <StudentRecordForm initial={editing} studentId={student.id} onSaved={() => setEditing(null)} />}</Dialog><ConfirmDialog confirmLabel="删除" onClose={() => setDeleting(null)} onConfirm={() => { if (deleting) remove.mutate(deleting.id, { onSuccess: () => setDeleting(null) }); }} open={deleting !== null} title="删除日常记录"><p>确定删除该日常记录吗？</p>{remove.isError && <p role="alert">删除失败，请重试。</p>}</ConfirmDialog></section>;
}
