import { useMemo, useState } from 'react';
import type { Student, StudentRecord } from '../../domain/entities';
import { studentRecordCategoryLabels, studentRecordRatingLabels, summarizeStudentRecords, type StudentRecordFilters } from '../../domain/studentOperations';
import { makeCsv, type ExportColumn } from '../../shared/export/csv';
import { downloadBytes, localDateStamp } from '../../shared/export/download';
import { makeXlsx } from '../../shared/export/xlsx';
import { Button } from '../../shared/ui/Button';
import { Field } from '../../shared/ui/Field';

const exportColumns: ExportColumn[] = [{ key: 'studentName', label: '学生姓名' }, { key: 'date', label: '日期' }, { key: 'categoryLabel', label: '类别' }, { key: 'ratingLabel', label: '等级' }, { key: 'content', label: '内容' }, { key: 'followUp', label: '后续跟进' }];

export function StudentSummary({ records, students }: { records: StudentRecord[]; students: Student[] }) {
  const [filters, setFilters] = useState<StudentRecordFilters>({}); const rows = useMemo(() => summarizeStudentRecords(filters, records, students), [filters, records, students]);
  const exportRows = rows.map((row) => ({ studentName: row.studentName, date: row.date, categoryLabel: row.categoryLabel, ratingLabel: row.ratingLabel, content: row.content, followUp: row.followUp }));
  const exportFile = (format: 'csv' | 'xlsx') => { const filename = `学生记录汇总-${localDateStamp()}.${format}`; if (format === 'csv') downloadBytes(makeCsv(exportColumns, exportRows), filename, 'text/csv;charset=utf-8'); else downloadBytes(makeXlsx('学生记录汇总', exportColumns, exportRows), filename, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); };
  return <section><div className="student-filters"><label className="field"><span className="field-label">学生筛选</span><select aria-label="学生筛选" value={filters.studentId ?? ''} onChange={(event) => setFilters({ ...filters, studentId: event.target.value || undefined })}><option value="">全部学生</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name}{student.archivedAt !== null ? '（已归档）' : ''}</option>)}</select></label><Field aria-label="开始日期" label="开始日期" type="date" value={filters.dateFrom ?? ''} onChange={(event) => setFilters({ ...filters, dateFrom: event.target.value || undefined })} /><Field aria-label="结束日期" label="结束日期" type="date" value={filters.dateTo ?? ''} onChange={(event) => setFilters({ ...filters, dateTo: event.target.value || undefined })} /><label className="field"><span className="field-label">类别筛选</span><select aria-label="类别筛选" value={filters.category ?? ''} onChange={(event) => setFilters({ ...filters, category: (event.target.value || undefined) as StudentRecord['category'] | undefined })}><option value="">全部类别</option>{Object.entries(studentRecordCategoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field"><span className="field-label">等级筛选</span><select aria-label="等级筛选" value={filters.rating ?? ''} onChange={(event) => setFilters({ ...filters, rating: (event.target.value || undefined) as StudentRecord['rating'] | undefined })}><option value="">全部等级</option>{Object.entries(studentRecordRatingLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><div className="page-actions"><Button variant="secondary" onClick={() => exportFile('csv')}>导出学生记录汇总 CSV</Button><Button variant="secondary" onClick={() => exportFile('xlsx')}>导出学生记录汇总 XLSX</Button></div><p>共 {rows.length} 条日常记录</p>{rows.length ? <div className="table-wrapper"><table className="responsive-table"><caption>学生记录汇总</caption><thead><tr><th>学生</th><th>日期</th><th>类别</th><th>等级</th><th>内容</th><th>后续跟进</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td data-label="学生">{row.studentName}</td><td data-label="日期">{row.date}</td><td data-label="类别">{row.categoryLabel}</td><td data-label="等级">{row.ratingLabel}</td><td data-label="内容">{row.content}</td><td data-label="后续跟进">{row.followUp || '—'}</td></tr>)}</tbody></table></div> : <p>暂无符合条件的日常记录。</p>}</section>;
}
