import { useMemo, useState } from 'react';
import type { Idea } from '../../domain/entities';
import { Button } from '../../shared/ui/Button';
import { Dialog } from '../../shared/ui/Dialog';
import { EmptyState } from '../../shared/ui/EmptyState';
import { IdeaForm } from './IdeaForm';
import { useConvertIdea, useIdeas, useUpdateIdea } from './ideaQueries';

export function IdeaPage() {
  const query = useIdeas(); const update = useUpdateIdea(); const convert = useConvertIdea(); const [showArchived, setShowArchived] = useState(false); const [editing, setEditing] = useState<Idea | null>(null); const ideas = useMemo(() => (query.data ?? []).filter((idea) => showArchived ? !!idea.archivedAt : !idea.archivedAt).sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.updatedAt.localeCompare(a.updatedAt)), [query.data, showArchived]);
  return <section className="idea-page" aria-labelledby="idea-page-title"><header className="page-header"><div><h2 id="idea-page-title">灵感记录</h2><p>快速捕捉，随后转为可执行的工作。</p></div><Button variant="secondary" onClick={() => setShowArchived(!showArchived)}>{showArchived ? '查看进行中' : '查看已归档'}</Button></header><IdeaForm compact onSaved={() => undefined} />{query.isPending && <p role="status">正在加载灵感……</p>}{query.isError && <p role="alert">灵感加载失败，请刷新后重试。</p>}{!query.isPending && !query.isError && ideas.length === 0 && <EmptyState title={showArchived ? '暂无已归档灵感' : '暂无进行中的灵感'} description="写下一句想法即可开始。" />}{ideas.length > 0 && <ul className="content-cards">{ideas.map((idea) => <li key={idea.id}><div><h3>{idea.content}{idea.pinned && <span className="pinned-badge">已置顶</span>}</h3><p>{idea.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</p></div><div className="card-actions"><Button aria-label={`${idea.pinned ? '取消置顶' : '置顶'}${idea.content}`} variant="ghost" onClick={() => update.mutate({ id: idea.id, patch: { pinned: !idea.pinned } })}>{idea.pinned ? '取消置顶' : '置顶'}</Button><Button aria-label={`${idea.archivedAt ? '恢复' : '归档'}${idea.content}`} variant="ghost" onClick={() => update.mutate({ id: idea.id, patch: { archivedAt: idea.archivedAt ? null : new Date().toISOString() } })}>{idea.archivedAt ? '恢复' : '归档'}</Button><Button aria-label={`编辑${idea.content}`} variant="ghost" onClick={() => setEditing(idea)}>编辑</Button>{!idea.archivedAt && <><Button aria-label={`转为待办${idea.content}`} disabled={convert.isPending} variant="ghost" onClick={() => convert.mutate({ idea, target: 'todo' })}>转为待办</Button><Button aria-label={`转为科研${idea.content}`} disabled={convert.isPending} variant="ghost" onClick={() => convert.mutate({ idea, target: 'research' })}>转为科研</Button><Button aria-label={`转为备课${idea.content}`} disabled={convert.isPending} variant="ghost" onClick={() => convert.mutate({ idea, target: 'lesson' })}>转为备课</Button></>}</div></li>)}</ul>}<Dialog open={!!editing} onClose={() => setEditing(null)} title="编辑灵感"><IdeaForm initial={editing ?? undefined} onSaved={() => setEditing(null)} /></Dialog></section>;
}
