import { useMemo, useState } from 'react';
import type { Mentorship, Teacher } from '../../domain/entities';
import { filterMentorships } from '../../domain/teacherOperations';
import { makeCsv, type ExportColumn } from '../../shared/export/csv';
import { downloadBytes, localDateStamp } from '../../shared/export/download';
import { makeXlsx } from '../../shared/export/xlsx';
import { Button } from '../../shared/ui/Button';

const statusLabel: Record<Mentorship['status'], string> = { planned: '计划中', active: '进行中', completed: '已完成', paused: '已暂停' };
const exportColumns: ExportColumn[] = [{ key: 'studentName', label: '学生姓名' }, { key: 'teacherName', label: '导师姓名' }, { key: 'academicYear', label: '学年' }, { key: 'grade', label: '年级' }, { key: 'major', label: '专业' }, { key: 'topic', label: '指导主题' }, { key: 'status', label: '进展' }];

export function MentorshipSummary({ mentorships, teachers }: { mentorships: Mentorship[]; teachers: Teacher[] }) {
  const [filters, setFilters] = useState({ academicYear: '', teacherId: '', grade: '', status: '' as Mentorship['status'] | '' });
  const records = useMemo(() => filterMentorships(mentorships, filters), [mentorships, filters]);
  const years = [...new Set(mentorships.map((item) => item.academicYear))].sort().reverse();
  const grades = [...new Set(mentorships.map((item) => item.grade))].sort();
  const exportRows = records.map((item) => ({ studentName: item.studentName, teacherName: teachers.find((teacher) => teacher.id === item.teacherId)?.name ?? '未知教师', academicYear: item.academicYear, grade: item.grade, major: item.major, topic: item.topic, status: statusLabel[item.status] }));
  const exportFile = (format: 'csv' | 'xlsx') => { const filename = `科研导师汇总-${localDateStamp()}.${format}`; if (format === 'csv') downloadBytes(makeCsv(exportColumns, exportRows), filename, 'text/csv;charset=utf-8'); else downloadBytes(makeXlsx('科研导师汇总', exportColumns, exportRows), filename, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); };
  return <section><div className="todo-filters"><label className="field"><span className="field-label">学年筛选</span><select aria-label="学年筛选" value={filters.academicYear} onChange={(event) => setFilters({ ...filters, academicYear: event.target.value })}><option value="">全部学年</option>{years.map((year) => <option key={year}>{year}</option>)}</select></label><label className="field"><span className="field-label">教师筛选</span><select aria-label="教师筛选" value={filters.teacherId} onChange={(event) => setFilters({ ...filters, teacherId: event.target.value })}><option value="">全部教师</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select></label><label className="field"><span className="field-label">年级筛选</span><select aria-label="年级筛选" value={filters.grade} onChange={(event) => setFilters({ ...filters, grade: event.target.value })}><option value="">全部年级</option>{grades.map((grade) => <option key={grade}>{grade}</option>)}</select></label><label className="field"><span className="field-label">进展筛选</span><select aria-label="进展筛选" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value as Mentorship['status'] | '' })}><option value="">全部状态</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><div className="page-actions"><Button variant="secondary" onClick={() => exportFile('csv')}>导出导师汇总 CSV</Button><Button variant="secondary" onClick={() => exportFile('xlsx')}>导出导师汇总 XLSX</Button></div><p>共 {records.length} 名学生</p><div className="table-wrapper"><table className="responsive-table"><caption>科研导师汇总</caption><thead><tr><th>学生</th><th>教师</th><th>学年</th><th>年级</th><th>专业</th><th>主题</th><th>进展</th></tr></thead><tbody>{records.map((item) => <tr key={item.id}><td data-label="学生">{item.studentName}</td><td data-label="教师">{teachers.find((teacher) => teacher.id === item.teacherId)?.name ?? '未知教师'}</td><td data-label="学年">{item.academicYear}</td><td data-label="年级">{item.grade}</td><td data-label="专业">{item.major}</td><td data-label="主题">{item.topic}</td><td data-label="进展">{statusLabel[item.status]}</td></tr>)}</tbody></table></div></section>;
}
